homework-5-task-1. Искандяров. 144
rinatisk/spbu_2021_kotlin_homeworks pull request #11
Opened 2021-04-01 12:21 UTC by rinatisk

2021-04-01 13:33 UTC, rinatisk commented
что лучше передавать -- укороченный список или позицию, с которой начинать парсинг? Если список, то наверно меньше вероятность, что выйдет за границы и нет путаницы с индексами?

2021-04-01 23:17 UTC, SpirinEgor requested changes

2021-04-01 23:17 UTC, SpirinEgor commented on src/main/kotlin/homework5/task-1.kt
> +        ("$value = ($leftChild ${operator.sign} $rightChild)").toString()
Это же не соответствует формату задания

2021-04-01 23:17 UTC, SpirinEgor commented on src/main/kotlin/homework5/task-1.kt
> +            (parseList.first() == "(") -> {
Ты же заменяешь все скобочки, а функция приватная. Так что можно не учитывать это.

2021-04-02 08:12 UTC, rinatisk commented on src/main/kotlin/homework5/task-1.kt
> +            (parseList.first() == "(") -> {
Я открывающуюся не заменяю, просто пробел добавляю, чтобы они не слипались с операторами

2021-04-04 11:13 UTC, SpirinEgor approved these changes

2021-04-04 11:13 UTC, merged