2-homework-1-task. Искандяров. 144 группа
rinatisk/spbu_2021_kotlin_homeworks pull request #5
Opened 2021-03-08 18:46 UTC by rinatisk

2021-03-09 14:58 UTC, nbirillo requested changes

2021-03-09 14:58 UTC, nbirillo commented on build.gradle.kts
> +            configureEach() {
Ну кажется, что хотелось бы генерировать для всей `src` папки

2021-03-09 14:58 UTC, nbirillo commented on src/main/kotlin/action/action.md
> +# Package action
Вот это кажется не хочется чтобы генерировалось каждый раз и добавлялось вообще в гит

2021-03-09 14:58 UTC, nbirillo commented on src/main/kotlin/action/InsertTail.kt
> + * Add number to head of list or reverse it
Чет просто копировать не прокатит))) оно не в голову добавляет

2021-03-09 15:12 UTC, rinatisk commented on src/main/kotlin/action/action.md
> +# Package action
Это не сгенерировалось, я добавил, чтобы к пакетам была тоже какая-то информация

2021-03-10 06:55 UTC, nbirillo commented on src/main/kotlin/action/action.md
> +# Package action
а зачем?)

2021-03-10 06:55 UTC, nbirillo commented on src/main/kotlin/action/action.md
> +# Package action
если они все равно не заполнены никакой инфой

2021-03-12 09:23 UTC, nbirillo requested changes
А добавь, пожалуйста, в ридми информацию, как создать документацию и где она будет лежать, раз уж нет кастомизации таски)

2021-03-18 22:50 UTC, elena-lyulina requested changes
Еще чуть-чуть и будет хорошо :)

2021-03-18 22:50 UTC, elena-lyulina commented on src/main/kotlin/action/InsertHead.kt
> + * Action subclass
У тебя первое предложение будет в сгенеренной документации выдаваться как короткое описание всего происходящего. Как думаешь, насколько твое первое предложение описывает все? Поменяй, пожалуйста, здесь и везде дальше, а еще лучше почитай, как работают javadoc https://www.oracle.com/ru/technical-resources/articles/java/javadoc-tool.html#descriptions

В идеале еще и точку надо не забывать ставить в конце, начинать его с большой буквы + c [стайлгайдом](https://www.oracle.com/ru/technical-resources/articles/java/javadoc-tool.html#styleguide) тоже надо ознакомится и поправить все под него

2021-03-23 09:30 UTC, elena-lyulina approved these changes
Класс, выглядит хорошо

2021-03-23 09:30 UTC, merged