2-homework-3-task. Искандяров. 144 группа
rinatisk/spbu_2021_kotlin_homeworks pull request #7
Opened 2021-03-14 18:30 UTC by rinatisk

2021-03-14 18:38 UTC, rinatisk commented
Не знаю как сделать сериализацию для той архитектуры, которая была изначально. Чуть-чуть подогнал под пример из гайда: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#registered-subclasses

2021-03-23 07:07 UTC, elena-lyulina requested changes
Порадовало использование ресурсов :)

2021-03-23 07:07 UTC, elena-lyulina commented on .github/workflows/main.yml
> +        run: .\gradlew.bat detekt
А зачем в этой задаче билд на windows нужен?

2021-03-23 07:07 UTC, elena-lyulina commented on src/main/kotlin/commandstorage/CommandStorage.kt
> +        private val format = Json { serializersModule = module }
посмтри на [kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html#class-layout), и не пиши property класса где-то в середине, пожалуйста. Сначала должны идти все properties, потом уже объявления методов и потом companion object

2021-03-23 07:07 UTC, elena-lyulina commented on src/main/kotlin/commandstorage/CommandStorage.kt
>      private val _numberList = mutableListOf<Int>()
Или я что-то не понимаю, или ты можешь сразу сделать val numberList = mutableListOf<Int>, не делая его private, так как он и не совсем private у тебя -- ты же написал к нему геттер ниже. А сеттера для него и так не будет, он же val, так что все хорошо и можно ограничиться только одной строчкой вместо использования backing properties

2021-03-23 07:07 UTC, elena-lyulina commented on src/main/kotlin/homework2/task3.kt
> +   // val resource = getResource()
комментарии подобного типа убираем из PR

2021-03-24 18:27 UTC, elena-lyulina approved these changes
Класс, спасибо

2021-03-24 18:27 UTC, merged