3-homework-2-task. Искандяров. 144 группа
rinatisk/spbu_2021_kotlin_homeworks pull request #9
Opened 2021-03-18 17:04 UTC by rinatisk

2021-03-18 19:21 UTC, cupertank commented
Подмерджи изменения из мастера, которые из первого задания, чтобы сразу проверка на винде была

2021-03-18 19:40 UTC, rinatisk commented
энивей тут много лишнего в диффах, потому что мне 2.3 не приняли ещё и возможно чето поменяется

2021-03-18 19:49 UTC, cupertank commented
ну ничо, я тогда помогу Насте)))))

2021-03-19 01:26 UTC, cupertank requested changes
В целом очень неплохо, удачи!!!!!

2021-03-19 01:26 UTC, cupertank commented on src/main/kotlin/commandstorage/CommandStorage.kt
> +    private val format = Json { serializersModule = module }
Во-первых подобные вещи можно положить в companion object, зачем они в каждом экземпляре класса непонятно. Во-вторых, кажется, проблему такого вида можно легко разрешить если Action будет не интерфейсом, а sealed class'ом.

2021-03-19 01:26 UTC, cupertank commented on src/main/kotlin/homework2/task3.kt
> +fun getResource(): String = object {}.javaClass.getResource("serialization.json").file
Во-первых я думаю, что подобные вещи можно куда-нибудь в Utils уносить и тебе не придется делать пустой объект. К тому же, я думаю стоит передавать название файла в подобного рода функции, а не хардкодить его.

2021-03-19 01:26 UTC, cupertank commented on src/main/kotlin/homework2/task3.kt
> +    commandStorage.writeSerialization(resource)
Записывать что либо обратно в ресурсы после выполнения программы не ок, ну да ладно.....

2021-03-19 01:26 UTC, cupertank commented on src/main/kotlin/commandstorage/CommandStorage.kt
> +        format.decodeFromString<MutableList<Action>>(toRead).map { doAction(it) }
map используется для применения какого-то действия для всей последовательности и **записи** в другую. Если тебе надо просто применить какое-то действие к последовательности, то следует использовать forEach

2021-03-19 01:26 UTC, cupertank commented on src/test/kotlin/action/InsertHeadTest.kt
> +        (1..4).map { commandStorage.doAction(InsertHead(it)) }
Аналогичный map

2021-03-19 01:26 UTC, cupertank commented on src/test/kotlin/action/MoveTest.kt
> +        @JvmStatic
Эта аннотация реально нужна?

2021-03-19 01:26 UTC, cupertank commented on src/test/kotlin/commandstorage/CommandStorageTest.kt
> +        assertEquals(inputData, File(getResource()).readText())
А вот тут точно не стоит записывать в ресурсы. Посмотри в сторону TemporaryFolder в JUnit'е

2021-03-19 01:26 UTC, cupertank commented on src/test/kotlin/commandstorage/CommandStorageTest.kt
> +        assertEquals(inputData, commandstorage.numberList)
Мне не нравится последовательность действий...
Ты что-то куда-то опять записываешь, потом читаешь, когда ты можешь написать заранее всё необходимое в ресурсы тестов

2021-03-19 11:34 UTC, cupertank commented on src/test/kotlin/action/InsertHeadTest.kt
> +        (1..4).map { commandStorage.doAction(InsertHead(it)) }
И вообще перепиши подобные вещи на for (i in 1..4){...}
Ибо оно выглядит как-то очень дико

2021-03-20 06:43 UTC, rinatisk commented
последний коммит - это только логи тестов добавил, которые для красоты. Все осмысленное было вроде до софта

2021-03-23 19:46 UTC, cupertank requested changes

2021-03-23 19:46 UTC, cupertank commented on src/main/kotlin/commandstorage/CommandStorage.kt
> +        private val module = SerializersModule {
И все же думаю, что sealed class был бы лучше, но дело твое, это не претензия

2021-03-23 19:46 UTC, cupertank commented on src/main/kotlin/commandstorage/CommandStorage.kt
> +        format.decodeFromString<MutableList<Action>>(toRead).map { doAction(it) }
Я не знаю, но ты просто проигнорировал мой спич на три строки с прошлого раза здесь. Если что, то я толсто тебе намекнул, что в данном случае нужно использовать forEach а не map

2021-03-23 19:46 UTC, cupertank commented on src/test/kotlin/action/MoveTest.kt
> +internal class MoveTest {
Возможно в прошлый раз забыл добавить (но ты так и так не успел в дедлайн), добавь тесты с неверными границами для мува при помощи assertThrows

2021-03-23 19:46 UTC, cupertank commented on src/test/kotlin/commandstorage/CommandStorageTest.kt
> +}
В тестах тебе не нужен утил для обращения к ресурсам. Ты можешь использовать javaClass от класса теста

2021-03-23 19:46 UTC, cupertank commented on src/test/kotlin/commandstorage/CommandStorageTest.kt
> +        val inputData = "[{\"type\":\"InsertTail\",\"number\":1},{\"type\":\"InsertTail\",\"number\":2}]"
Предлагаю это унести в ресурсы и читать оттуда

2021-03-23 19:46 UTC, cupertank commented on src/test/kotlin/commandstorage/CommandStorageTest.kt
> +        val tempResource: Path = tempDir.resolve("temp.json")
Тип указывать не нужно)

2021-03-23 19:46 UTC, cupertank commented on src/test/kotlin/commandstorage/CommandStorageTest.kt
> +    @ExperimentalPathApi
Тебе точно все ещё нужна эта аннотация? Если да, то ответь в реплае для чего

2021-03-24 16:59 UTC, rinatisk commented on src/main/kotlin/commandstorage/CommandStorage.kt
> +        private val module = SerializersModule {
новый action добавить будет сложнее тогда, придется лезть в класс предок, если я правильно понимаю?

2021-04-01 13:40 UTC, cupertank approved these changes

2021-04-01 13:40 UTC, cupertank commented on build.gradle.kts
> +    implementation("org.junit.jupiter:junit-jupiter:5.4.2")
это должно быть testImplementation. Синхронизируй версии тогда уже заодно

2021-04-01 13:49 UTC, merged